## @section Container image parameters
## Parameters about the container image to pull and deploy to the cluster.
## As of now, the repository, pullPolicy, imagePullSecrets and tag can be specified.

## @param image.registry The registry where to pull the image, e.g. ghcr or docker.io
## @param image.repository The repository inside the registry where to pull the image
## @param image.tag The tag for the image
## @param image.pullPolicy The pull policy for the image
## @param image.pullSecrets An array of pull secrets to use to authenticate to the repository
##
image:
  registry:  ghcr.io
  repository: cloudnativesdwan/cnwan-operator
  tag: v0.5.0
  pullPolicy: Always
  pullSecrets: []


## @section Operator settings
## Parameters to modify the behavior of the operator and deploy its settings.
## ref: https://github.com/CloudNativeSDWAN/cnwan-operator/blob/master/README.md#documentation
##

## Operator settings
# ref: https://github.com/CloudNativeSDWAN/cnwan-operator/blob/master/docs/configuration.md
#
operator:
  ## @param operator.namespaceListPolicy The namespace list policy: allowlist or blocklist
  ##
  namespaceListPolicy: allowlist

  ## @param operator.serviceAnnotations The annotations to look for in a service
  ##
  serviceAnnotations: []

  ## @param operator.serviceRegistry The service registry to use: etcd or gcpServiceDirectory
  ##
  serviceRegistry: <service-registry>

  ## Google Service Directory settings
  ## ref: https://github.com/CloudNativeSDWAN/cnwan-operator/blob/master/docs/gcp_service_directory/configure_with_operator.md
  ##
  googleServiceDirectory:

    ## @param operator.googleServiceDirectory.serviceAccount The path to the service account to use to
    ## authenticate to GCP. **DO NOT** set this explicitly, but rather supply this information during
    ## installation with --set-file, e.g. `--set-file
    ## settings.googleServiceDirectory.serviceAccountPath=/path/to/serviceAccount.json` .
    ##
    serviceAccount: ""

    ## @param operator.googleServiceDirectory.defaultRegion The default region to use for Service Directory.
    ## You *must* specify this, unless you are running in GKE *and* want to use
    ## the current region, in which case you can just omit this.
    ##
    defaultRegion: <region>

    ## @param operator.googleServiceDirectory.projectID The preject ID where Service Directory is enabled.
    ## You *must* specify this, unless you are running in GKE *and* want to use
    ## the current region, in which case you can just comment this.
    ##
    projectID: <project-id>

  ## etcd settings
  ## ref: https://github.com/CloudNativeSDWAN/cnwan-operator/blob/master/docs/etcd/operator_configuration.md
  ##
  etcd:

    ## @param operator.etcd.install Whether to install etcd in the current namespace.
    ## Set this to false or omit this if you plan to install it yourself or already have it running somewhere.
    ##
    install: false

    ## @param operator.etcd.username The username to connect as
    ##
    username: root

    ## @param operator.etcd.password The password to use for the username above
    ##
    password: "dem0-pwd"

    ## @param operator.etcd.prefix The prefix that all keys will share
    ##
    prefix: "/service-registry"

    ## @param operator.etcd.endpoints A list of endpoints where your etcd nodes are serving from.
    ## If `operator.etcd.install is true, this will be filled automatically.
    ##
    endpoints:
      - "etcd.etcd:2379"

  ## Cloud metadata settings
  ## ref: https://github.com/CloudNativeSDWAN/cnwan-operator/blob/master/docs/configuration.md#cloud-metadata
  ##
  cloudMetadata:
    ## @param operator.cloudMetadata.network Whether to register the current network name (VPC).
    ## Set auto if you are running in GKE to retrieve this value automatically.
    ## Omit if you don't need this.
    ##
    network: <network>
  
    ## @param operator.cloudMetadata.subNetwork Whether to register the current sub-network name.
    ## Set auto if you are running in GKE to retrieve this value automatically.
    ## Omit if you don't need this.
    ##
    subNetwork: <sub-network>

## Bitnami/etcd settings
## Options about the etcd dependency that will be installed along the operator
## if operator.etcd.install is true.
# #These are ignored if operator.etcd.install is false, in which case modifying
## these values will not have any effect.
## ref: https://github.com/bitnami/charts/tree/master/bitnami/etcd
##
etcd:
  fullnameOverride: service-registry

  service:
    type: ClusterIP

  auth:
    rbac:
      enabled: true
      allowNoneAuthentication: false
      existingSecret: etcd-root-password
