apiVersion: v1
entries:
  etcd:
  - annotations:
      category: Database
    apiVersion: v2
    appVersion: 3.5.0
    created: "2021-08-11T11:03:59.864038+02:00"
    dependencies:
    - name: common
      repository: https://charts.bitnami.com/bitnami
      tags:
      - bitnami-common
      version: 1.x.x
    description: etcd is a distributed key value store that provides a reliable way
      to store data across a cluster of machines
    digest: f9e4b21559e5e84caf5c5f2d2a1f5c34536cad58eb8b2b00e0e8328791f0a01c
    home: https://github.com/bitnami/charts/tree/master/bitnami/etcd
    icon: https://bitnami.com/assets/stacks/etcd/img/etcd-stack-220x234.png
    keywords:
    - etcd
    - cluster
    - database
    - cache
    - key-value
    maintainers:
    - email: containers@bitnami.com
      name: Bitnami
    name: etcd
    sources:
    - https://github.com/bitnami/bitnami-docker-etcd
    - https://coreos.com/etcd/
    urls:
    - https://github.com/SunSince90/test-chart/charts/etcd-6.2.9.tgz
    version: 6.2.9
generated: "2021-08-11T11:03:59.860759+02:00"
