name: Generate Chart Readme

on:
  pull_request:
    paths:
      - 'charts/cnwan-operator/values.yaml'

jobs:
  generate-chart-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout norwoodj/helm-docs
        uses: actions/checkout@v2
        with:
          repository: norwoodj/helm-docs
          path: readme-generator

      - name: Setup go
        uses: actions/setup-go@v2

      - name: Cache go mod
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install helm-docs
        run: cd readme-generator/cmd/helm-docs && go build -a -o helm-docs *.go

      - name: Checkout to repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          path: charts

      - name: Generate Readme
        run: ./readme-generator/cmd/helm-docs/helm-docs ./charts/cnwan-operator

      - run: pwd
      - run: ls
      - run: tree .

      # - name: Output generated README.md
      #   run: cd charts && cat ./charts/cnwan-operator/README.md

      - run: |
          cd charts
          git config user.email actions@github.com
          git config user.name "Readme generator"
          git add ./charts/cnwan-operator/README.md
          git commit -m "Generate README.md" -s
          git push
      # - uses: stefanzweifel/git-auto-commit-action@v2.3.0
      #   with:
      #     commit_message: Apply automatic changes
      #     branch: ${{ github.head_ref }}

      #     # Optional git params
      #     commit_options: '--no-verify --signoff'

      #     # Optional glob pattern of files which should be added to the commit
      #     file_pattern: ./charts/cnwan-operator/README.md
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
