name: Generate Chart Readme

on:
  pull_request:
    paths:
      - 'charts/cnwan-operator/values.yaml'

jobs:
  generate-chart-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout norwoodj/helm-docs
        uses: actions/checkout@v2
        with:
          repository: norwoodj/helm-docs
          path: readme-generator

      - name: Setup go
        uses: actions/setup-go@v2

      - name: Cache go mod
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install helm-docs
        run: cd readme-generator/cmd/helm-docs && go build -a -o helm-docs *.go

      - name: Checkout to repo
        uses: actions/checkout@v2
        with:
          path: charts

      - name: Generate Readme
        run: cd charts && $GITHUB_WORKSPACE/readme-generator/cmd/helm-docs/helm-docs
